"""
models.py — Pydantic models for all new Round 3 collections.
These define the shape of every document written to MongoDB.
"""

from pydantic import BaseModel, Field
from typing import Optional, List, Literal
from datetime import datetime
from enum import Enum


# ─────────────────────────────────────────────
# ENUMS
# ─────────────────────────────────────────────

class VehicleCategory(str, Enum):
    HEAVY = "HEAVY"          # TRUCK, BUS, VAN
    CAR = "CAR"              # CAR, PICKUP
    TWO_WHEELER = "TWO_WHEELER"  # BIKE, SCOOTY

class TicketStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    OVERDUE = "overdue"
    GROUNDED = "grounded"    # P0 critical — vehicle must not run

class TicketPriority(str, Enum):
    P0 = "P0"   # Critical  — ground vehicle, fix within 24h
    P1 = "P1"   # Warning   — fix within 7 days
    P2 = "P2"   # Info      — fold into next routine service

class TicketSource(str, Enum):
    ROUTINE = "routine"       # Generated by odometer/time interval check
    PREDICTIVE = "predictive" # Auto-generated from Round 2 alert engine
    MANUAL = "manual"         # Created by owner or mechanic directly

class UserRole(str, Enum):
    MECHANIC = "mechanic"
    OWNER = "owner"
    INSURANCE = "insurance"
    SUPER_ADMIN = "super_admin"

class ServiceType(str, Enum):
    OIL_CHANGE = "Oil Change"
    TYRE_SERVICE = "Tyre Service"
    BRAKE_INSPECTION = "Brake Inspection"
    BATTERY_CHECK = "Battery Check"
    FULL_INSPECTION = "Full Inspection"
    COOLING_SYSTEM = "Cooling System Check"
    AIR_BRAKE_INSPECTION = "Air Brake Inspection"
    DPF_CLEAN = "DPF Clean & Forced Regen"
    DRIVETRAIN = "Drivetrain Tensioning"
    STRUCTURAL_INSPECTION = "Structural & Fluid Leak Inspection"
    SPARK_PLUG = "Spark Plug & Coil Inspection"
    SUSPENSION = "Suspension Check"
    CHAIN_LUBE = "Chain Lubrication & Tensioning"
    BRAKE_PAD = "Brake Pad Replacement"
    CUSTOM = "Custom"


# ─────────────────────────────────────────────
# 1. ORGANIZATIONS
# ─────────────────────────────────────────────

class Organization(BaseModel):
    """
    Groups vehicles under a fleet owner / company.
    Controls visibility — users only see their org's vehicles.
    """
    org_id: str                     # e.g. "ORG-001"
    name: str                       # e.g. "Chennai Metro Transport"
    contact_email: str
    vehicle_ids: List[str] = []     # e.g. ["TRUCK-001", "BUS-003"]
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_active: bool = True


# ─────────────────────────────────────────────
# 2. USERS (RBAC)
# ─────────────────────────────────────────────

class User(BaseModel):
    """
    User account with role-based access.
    Role determines which portal they see after login.
    """
    user_id: str                    # e.g. "USR-001"
    username: str
    hashed_password: str
    role: UserRole
    org_id: Optional[str] = None    # None only for SUPER_ADMIN
    full_name: str
    email: str
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_active: bool = True
    last_login: Optional[datetime] = None


# ─────────────────────────────────────────────
# 3. MAINTENANCE SCHEDULE (Interval Rules)
# ─────────────────────────────────────────────

class MaintenanceSchedule(BaseModel):
    """
    Defines routine service intervals per vehicle category and type.
    The scheduling engine reads these rules to auto-generate tickets.

    Rule: ticket fires when EITHER km_interval OR days_interval is exceeded.
    """
    schedule_id: str                    # e.g. "SCHED-HEAVY-OIL"
    vehicle_category: VehicleCategory
    vehicle_types: List[str]            # e.g. ["TRUCK", "BUS", "VAN"]
    service_type: ServiceType
    km_interval: Optional[int] = None  # e.g. 20000 (km)
    days_interval: Optional[int] = None # e.g. 180 (days)
    warning_km_before: int = 500       # start alerting 500 km before due
    warning_days_before: int = 7       # start alerting 7 days before due
    checklist_items: List[str] = []    # default checklist for this service
    created_at: datetime = Field(default_factory=datetime.utcnow)
    is_active: bool = True


# ─────────────────────────────────────────────
# 4. SERVICE HISTORY (The Ledger)
# ─────────────────────────────────────────────

class ChecklistItem(BaseModel):
    item: str
    completed: bool = False
    notes: Optional[str] = None

class ServiceHistory(BaseModel):
    """
    Immutable record of every completed service event.
    Written when a mechanic submits the 'Complete Service' form.
    Never deleted — insurance portal reads from this.
    """
    event_id: str                       # e.g. "SVC-20260305-CAR001"
    vehicle_id: str                     # e.g. "CAR-001"
    vehicle_type: str                   # e.g. "CAR"
    org_id: str
    ticket_id: Optional[str] = None    # link back to the ticket that triggered this
    service_type: ServiceType
    mechanic_id: str
    mechanic_name: str
    odometer_at_service: float          # km reading at time of service
    service_date: datetime
    checklist: List[ChecklistItem] = []
    notes: str = ""
    cost_estimate: Optional[float] = None   # in INR
    parts_replaced: List[str] = []
    next_service_due_km: Optional[float] = None
    next_service_due_date: Optional[datetime] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ─────────────────────────────────────────────
# 5. MAINTENANCE TICKETS (Work Orders)
# ─────────────────────────────────────────────

class MaintenanceTicket(BaseModel):
    """
    A work order — either upcoming, in-progress, or overdue.
    Created automatically by the scheduler or predictive alert bridge,
    or manually by an owner/mechanic.
    """
    ticket_id: str                          # e.g. "TKT-20260305-TRUCK001-001"
    vehicle_id: str
    vehicle_type: str
    org_id: str

    service_type: ServiceType
    source: TicketSource                    # routine | predictive | manual
    priority: TicketPriority                # P0 | P1 | P2

    status: TicketStatus = TicketStatus.PENDING

    # Why this ticket was created
    trigger_reason: str                     # e.g. "Oil pressure dropped to 17 PSI"
    alert_id: Optional[str] = None         # Round 2 alert that triggered this (if predictive)

    # Scheduling
    created_at: datetime = Field(default_factory=datetime.utcnow)
    due_by: Optional[datetime] = None      # deadline for the fix
    approved_at: Optional[datetime] = None
    approved_by: Optional[str] = None      # owner user_id
    assigned_mechanic_id: Optional[str] = None

    # Vehicle state at creation time
    odometer_at_creation: Optional[float] = None
    health_score_at_creation: Optional[float] = None

    # Completion
    completed_at: Optional[datetime] = None
    service_event_id: Optional[str] = None  # links to ServiceHistory after done

    # Dynamic checklist (merged routine + predictive tasks)
    checklist: List[ChecklistItem] = []

    # For owner Kanban board
    owner_notes: str = ""
    is_delayed: bool = False
    delay_reason: Optional[str] = None
